### ISSUE TITLE
crypto issue in a task

### ISSUE THREAD

**Issue by erwangranger** [jharmison-redhat/oc-mirror-e2e#29]
I had to use slightly different images than the ones specified by default. I think it might be the cause of an error I encountered. 

I ended up with a failing task:

This
```yaml
- name: Generate self-signed private key for proxy
  community.crypto.openssl_privatekey:
    path: '{{ output_dir }}/squid.key'
``` 
failed with
```log
community.crypto.openssl_privatekey TypeError: deprecated() got an unexpected keyword argument 'name'
```

I [googled around](https://github.com/pyca/pyopenssl/issues/1151) and then I changed [this line](https://github.com/jharmison-redhat/oc-mirror-e2e/blob/62acf61c12af9daac93a1c90b30cef7c028650cf/collection/requirements.txt#L2) from `cryptography ~=36.0.1` to `cryptography ~=38` and helped me get past this error. 

Probably specific to my env, but figured I'd document/report it, in case others run into this.
